# Generated by Django 5.0.6 on 2024-06-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_artista',
            field=models.CharField(default='sin nombre', max_length=255, verbose_name='Nombre del Artista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_disco',
            field=models.CharField(default='Sin Nombre', max_length=255, verbose_name='Nombre del Disco'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
