# Generated by Django 5.0.6 on 2024-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_producto_nombre_producto_nombre_artista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_tapa',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
