# Generated by Django 5.0.6 on 2024-06-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_imagen_tapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_tapa',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
