"""
Django settings for tienda project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zl2(0ljfoj*_8t!f^90b%xnzx8!qnmf$g!4f-s13r)$@l*%1z!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'usuarios.CustomUser'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "carrito",
    "catalogo",
    "pedidos",
    "usuarios",
    'tienda',
    'autenticacion',    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tienda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#Configuracion de archivos estaticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Agrega la carpeta static global
]

#Configuracion de archivos de media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#deberia ser para que Index.html sea la pagina principal
AUTH_USER_MODEL = 'usuarios.CustomUser'
LOGIN_REDIRECT_URL = '/usuarios'
LOGOUT_REDIRECT_URL = '/catalogo'
LOGIN_URL = '/usuarios/login'

#esto es para que me tome el Username como requisito de Login y no que sea el Email.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    
]

# Configuración para el envío de correos electrónicos

# # Backend para el envío de correos electrónicos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# # Host del servidor SMTP que vas a usar (por ejemplo, Gmail)
EMAIL_HOST = 'smtp.gmail.com'

# # Puerto del servidor SMTP para conexiones seguras TLS (para Gmail es 587)
EMAIL_PORT = 587

# # Método de seguridad del servidor SMTP (TLS es común para Gmail)
EMAIL_USE_TLS = True

# # Dirección de correo electrónico desde la cual enviar los correos
EMAIL_HOST_USER = ''  # Reemplaza con tu dirección de Gmail o del servidor SMTP

# # Contraseña de la dirección de correo electrónico
EMAIL_HOST_PASSWORD = ''  # Reemplaza con la contraseña de tu correo electrónico

# # Dirección de correo electrónico opcional para recibir notificaciones de errores
# # EMAIL_ERROR_TO = ''  # Descomenta y completa si deseas recibir notificaciones de errores

# # Configuración adicional de correos electrónicos
DEFAULT_FROM_EMAIL = 'tu_correo@gmail.com'  # Reemplaza con tu dirección de Gmail o del servidor SMTP

# # URLs a las que Django permitirá enviar correos (permite todas si es None)
ALLOWED_HOSTS = []  # Ajusta según tus necesidades de seguridad

# # Configuración de la zona horaria de tu aplicación
TIME_ZONE = 'America/Lima'

# # Idioma de la interfaz de administración y las aplicaciones incluidas
LANGUAGE_CODE = 'es-pe'